name: Publish Artifacts to DockerHub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, 'release-please--branches--main')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven

      - name: Setup depends
        run: |
          pip install yq

      - name: Set extra environment and metadata
        id: metadata
        run: |
          CURRENT_VERSION=$(xq -r .project.version pom.xml)
          DOCKER_IMAGE_NAME=$(basename ${GITHUB_REPOSITORY})
          echo "DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME}" >> "$GITHUB_ENV"
          echo "ARTIFACT_VERSION=${CURRENT_VERSION}" >> "$GITHUB_ENV"
          echo "DOCKER_LATEST_IMAGE_TAG=${DOCKER_IMAGE_NAME}:latest" >> "$GITHUB_ENV"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: fabianbormann/${{ env.DOCKER_IMAGE_NAME }}
          short-description: The Ockr API is the main interface to interact with the Ockr ecosystem

      - name: Build and Push docker image
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          context: .
          push: true
          tags: |
            fabianbormann/${{ env.DOCKER_LATEST_IMAGE_TAG }}
            fabianbormann/${{ env.DOCKER_IMAGE_NAME }}:${{ env.ARTIFACT_VERSION }}
